### ISSUE TITLE
Periodically refresh viewer/views counts

### ISSUE THREAD

**Issue by dbernard** [dbernard/twitch-zoo#10]
Refresh the viewer and views counts for streamers every few seconds. This might make use of AJAX calls to the `/streamers` endpoint which just returns stream objects as JSON.

**Addressing this issue probably involves moving stream loading logic to JS.**

**Comment by dbernard** [comment]
~~I plan to pick this up next time I have a chance~~ _(I'm not going to get to this)_, but if anyone gets to it before me, by all means feel free to knock this out!

**Comment by dbernard** [comment]
I'm going to claim technical weakness and lack of time here and say there is no way I get this done the right way before game time. If anyone else wants to take a shot at it feel free

**Comment by arusahni** [comment]
I'll take this - I think it can integrate with some of the donation work I've been doing. If you get the chance, can you review #21 to assess whether or not my client-side JS approach meets with your approval?

**Comment by arusahni** [comment]
Also, @dbernard and @jaykwon - thoughts on going serverless? This will require that I hide some portion of the Twitch API querying behind our server (so we can securely use secrets). This can either be asyncio-based with a memcached cache (easy), a mix of wsgi and lambda (lambda solely for querying the API/elasticache), or entirely lambda (extralife.thehumangeo.com maps to the API gateway). I would use Zappa, so we'd still be able to develop locally.

**Comment by dbernard** [comment]
I like the idea, the caveat being that I personally am not super familiar with the serverless route outside of Lambda. Will the transition be doable with a week to go before Extra Life?

**Comment by arusahni** [comment]
I believe so.

**Comment by oxhacks** [comment]
I'm cool with going the serverless route, especially considering our (light) architecture lends itself well to that. Going asyncio and introducing an event loop would help us reduce the overhead of the various game stat calls in the future, so that would also be nice.
